/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfesionalesRouteImport } from './routes/profesionales'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosCategoriaRouteImport } from './routes/servicios.$categoria'
import { Route as ProfesionalesIdRouteImport } from './routes/profesionales.$id'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificacionesRouteImport } from './routes/_authenticated/notificaciones'
import { Route as AuthenticatedMiPerfilRouteImport } from './routes/_authenticated/mi-perfil'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProfesionalVerificacionRouteImport } from './routes/_authenticated/profesional.verificacion'
import { Route as AuthenticatedProfesionalPerfilRouteImport } from './routes/_authenticated/profesional.perfil'
import { Route as AuthenticatedProfesionalOportunidadesRouteImport } from './routes/_authenticated/profesional.oportunidades'
import { Route as AuthenticatedProfesionalMensajesRouteImport } from './routes/_authenticated/profesional.mensajes'
import { Route as AuthenticatedProfesionalCotizacionesRouteImport } from './routes/_authenticated/profesional.cotizaciones'
import { Route as AuthenticatedMensajesIdRouteImport } from './routes/_authenticated/mensajes.$id'
import { Route as AuthenticatedClienteSolicitudesRouteImport } from './routes/_authenticated/cliente.solicitudes'
import { Route as AuthenticatedClienteMensajesRouteImport } from './routes/_authenticated/cliente.mensajes'
import { Route as AuthenticatedAdminVerificacionesRouteImport } from './routes/_authenticated/admin.verificaciones'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin.categorias'
import { Route as AuthenticatedProfesionalOportunidadesIdRouteImport } from './routes/_authenticated/profesional.oportunidades.$id'
import { Route as AuthenticatedClienteSolicitudesNuevaRouteImport } from './routes/_authenticated/cliente.solicitudes.nueva'
import { Route as AuthenticatedClienteSolicitudesIdRouteImport } from './routes/_authenticated/cliente.solicitudes.$id'

const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalesRoute = ProfesionalesRouteImport.update({
  id: '/profesionales',
  path: '/profesionales',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosCategoriaRoute = ServiciosCategoriaRouteImport.update({
  id: '/$categoria',
  path: '/$categoria',
  getParentRoute: () => ServiciosRoute,
} as any)
const ProfesionalesIdRoute = ProfesionalesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProfesionalesRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacionesRoute =
  AuthenticatedNotificacionesRouteImport.update({
    id: '/notificaciones',
    path: '/notificaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiPerfilRoute = AuthenticatedMiPerfilRouteImport.update({
  id: '/mi-perfil',
  path: '/mi-perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfesionalVerificacionRoute =
  AuthenticatedProfesionalVerificacionRouteImport.update({
    id: '/profesional/verificacion',
    path: '/profesional/verificacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfesionalPerfilRoute =
  AuthenticatedProfesionalPerfilRouteImport.update({
    id: '/profesional/perfil',
    path: '/profesional/perfil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfesionalOportunidadesRoute =
  AuthenticatedProfesionalOportunidadesRouteImport.update({
    id: '/profesional/oportunidades',
    path: '/profesional/oportunidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfesionalMensajesRoute =
  AuthenticatedProfesionalMensajesRouteImport.update({
    id: '/profesional/mensajes',
    path: '/profesional/mensajes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfesionalCotizacionesRoute =
  AuthenticatedProfesionalCotizacionesRouteImport.update({
    id: '/profesional/cotizaciones',
    path: '/profesional/cotizaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMensajesIdRoute = AuthenticatedMensajesIdRouteImport.update({
  id: '/mensajes/$id',
  path: '/mensajes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClienteSolicitudesRoute =
  AuthenticatedClienteSolicitudesRouteImport.update({
    id: '/cliente/solicitudes',
    path: '/cliente/solicitudes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteMensajesRoute =
  AuthenticatedClienteMensajesRouteImport.update({
    id: '/cliente/mensajes',
    path: '/cliente/mensajes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVerificacionesRoute =
  AuthenticatedAdminVerificacionesRouteImport.update({
    id: '/verificaciones',
    path: '/verificaciones',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedProfesionalOportunidadesIdRoute =
  AuthenticatedProfesionalOportunidadesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedProfesionalOportunidadesRoute,
  } as any)
const AuthenticatedClienteSolicitudesNuevaRoute =
  AuthenticatedClienteSolicitudesNuevaRouteImport.update({
    id: '/nueva',
    path: '/nueva',
    getParentRoute: () => AuthenticatedClienteSolicitudesRoute,
  } as any)
const AuthenticatedClienteSolicitudesIdRoute =
  AuthenticatedClienteSolicitudesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedClienteSolicitudesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profesionales': typeof ProfesionalesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mi-perfil': typeof AuthenticatedMiPerfilRoute
  '/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profesionales/$id': typeof ProfesionalesIdRoute
  '/servicios/$categoria': typeof ServiciosCategoriaRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/verificaciones': typeof AuthenticatedAdminVerificacionesRoute
  '/cliente/mensajes': typeof AuthenticatedClienteMensajesRoute
  '/cliente/solicitudes': typeof AuthenticatedClienteSolicitudesRouteWithChildren
  '/mensajes/$id': typeof AuthenticatedMensajesIdRoute
  '/profesional/cotizaciones': typeof AuthenticatedProfesionalCotizacionesRoute
  '/profesional/mensajes': typeof AuthenticatedProfesionalMensajesRoute
  '/profesional/oportunidades': typeof AuthenticatedProfesionalOportunidadesRouteWithChildren
  '/profesional/perfil': typeof AuthenticatedProfesionalPerfilRoute
  '/profesional/verificacion': typeof AuthenticatedProfesionalVerificacionRoute
  '/cliente/solicitudes/$id': typeof AuthenticatedClienteSolicitudesIdRoute
  '/cliente/solicitudes/nueva': typeof AuthenticatedClienteSolicitudesNuevaRoute
  '/profesional/oportunidades/$id': typeof AuthenticatedProfesionalOportunidadesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profesionales': typeof ProfesionalesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mi-perfil': typeof AuthenticatedMiPerfilRoute
  '/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profesionales/$id': typeof ProfesionalesIdRoute
  '/servicios/$categoria': typeof ServiciosCategoriaRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/verificaciones': typeof AuthenticatedAdminVerificacionesRoute
  '/cliente/mensajes': typeof AuthenticatedClienteMensajesRoute
  '/cliente/solicitudes': typeof AuthenticatedClienteSolicitudesRouteWithChildren
  '/mensajes/$id': typeof AuthenticatedMensajesIdRoute
  '/profesional/cotizaciones': typeof AuthenticatedProfesionalCotizacionesRoute
  '/profesional/mensajes': typeof AuthenticatedProfesionalMensajesRoute
  '/profesional/oportunidades': typeof AuthenticatedProfesionalOportunidadesRouteWithChildren
  '/profesional/perfil': typeof AuthenticatedProfesionalPerfilRoute
  '/profesional/verificacion': typeof AuthenticatedProfesionalVerificacionRoute
  '/cliente/solicitudes/$id': typeof AuthenticatedClienteSolicitudesIdRoute
  '/cliente/solicitudes/nueva': typeof AuthenticatedClienteSolicitudesNuevaRoute
  '/profesional/oportunidades/$id': typeof AuthenticatedProfesionalOportunidadesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/profesionales': typeof ProfesionalesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mi-perfil': typeof AuthenticatedMiPerfilRoute
  '/_authenticated/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/profesionales/$id': typeof ProfesionalesIdRoute
  '/servicios/$categoria': typeof ServiciosCategoriaRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/verificaciones': typeof AuthenticatedAdminVerificacionesRoute
  '/_authenticated/cliente/mensajes': typeof AuthenticatedClienteMensajesRoute
  '/_authenticated/cliente/solicitudes': typeof AuthenticatedClienteSolicitudesRouteWithChildren
  '/_authenticated/mensajes/$id': typeof AuthenticatedMensajesIdRoute
  '/_authenticated/profesional/cotizaciones': typeof AuthenticatedProfesionalCotizacionesRoute
  '/_authenticated/profesional/mensajes': typeof AuthenticatedProfesionalMensajesRoute
  '/_authenticated/profesional/oportunidades': typeof AuthenticatedProfesionalOportunidadesRouteWithChildren
  '/_authenticated/profesional/perfil': typeof AuthenticatedProfesionalPerfilRoute
  '/_authenticated/profesional/verificacion': typeof AuthenticatedProfesionalVerificacionRoute
  '/_authenticated/cliente/solicitudes/$id': typeof AuthenticatedClienteSolicitudesIdRoute
  '/_authenticated/cliente/solicitudes/nueva': typeof AuthenticatedClienteSolicitudesNuevaRoute
  '/_authenticated/profesional/oportunidades/$id': typeof AuthenticatedProfesionalOportunidadesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/profesionales'
    | '/reset-password'
    | '/servicios'
    | '/admin'
    | '/dashboard'
    | '/mi-perfil'
    | '/notificaciones'
    | '/onboarding'
    | '/profesionales/$id'
    | '/servicios/$categoria'
    | '/admin/categorias'
    | '/admin/usuarios'
    | '/admin/verificaciones'
    | '/cliente/mensajes'
    | '/cliente/solicitudes'
    | '/mensajes/$id'
    | '/profesional/cotizaciones'
    | '/profesional/mensajes'
    | '/profesional/oportunidades'
    | '/profesional/perfil'
    | '/profesional/verificacion'
    | '/cliente/solicitudes/$id'
    | '/cliente/solicitudes/nueva'
    | '/profesional/oportunidades/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profesionales'
    | '/reset-password'
    | '/servicios'
    | '/admin'
    | '/dashboard'
    | '/mi-perfil'
    | '/notificaciones'
    | '/onboarding'
    | '/profesionales/$id'
    | '/servicios/$categoria'
    | '/admin/categorias'
    | '/admin/usuarios'
    | '/admin/verificaciones'
    | '/cliente/mensajes'
    | '/cliente/solicitudes'
    | '/mensajes/$id'
    | '/profesional/cotizaciones'
    | '/profesional/mensajes'
    | '/profesional/oportunidades'
    | '/profesional/perfil'
    | '/profesional/verificacion'
    | '/cliente/solicitudes/$id'
    | '/cliente/solicitudes/nueva'
    | '/profesional/oportunidades/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/profesionales'
    | '/reset-password'
    | '/servicios'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/mi-perfil'
    | '/_authenticated/notificaciones'
    | '/_authenticated/onboarding'
    | '/profesionales/$id'
    | '/servicios/$categoria'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/verificaciones'
    | '/_authenticated/cliente/mensajes'
    | '/_authenticated/cliente/solicitudes'
    | '/_authenticated/mensajes/$id'
    | '/_authenticated/profesional/cotizaciones'
    | '/_authenticated/profesional/mensajes'
    | '/_authenticated/profesional/oportunidades'
    | '/_authenticated/profesional/perfil'
    | '/_authenticated/profesional/verificacion'
    | '/_authenticated/cliente/solicitudes/$id'
    | '/_authenticated/cliente/solicitudes/nueva'
    | '/_authenticated/profesional/oportunidades/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProfesionalesRoute: typeof ProfesionalesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServiciosRoute: typeof ServiciosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesionales': {
      id: '/profesionales'
      path: '/profesionales'
      fullPath: '/profesionales'
      preLoaderRoute: typeof ProfesionalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/$categoria': {
      id: '/servicios/$categoria'
      path: '/$categoria'
      fullPath: '/servicios/$categoria'
      preLoaderRoute: typeof ServiciosCategoriaRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/profesionales/$id': {
      id: '/profesionales/$id'
      path: '/$id'
      fullPath: '/profesionales/$id'
      preLoaderRoute: typeof ProfesionalesIdRouteImport
      parentRoute: typeof ProfesionalesRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificaciones': {
      id: '/_authenticated/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof AuthenticatedNotificacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-perfil': {
      id: '/_authenticated/mi-perfil'
      path: '/mi-perfil'
      fullPath: '/mi-perfil'
      preLoaderRoute: typeof AuthenticatedMiPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profesional/verificacion': {
      id: '/_authenticated/profesional/verificacion'
      path: '/profesional/verificacion'
      fullPath: '/profesional/verificacion'
      preLoaderRoute: typeof AuthenticatedProfesionalVerificacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profesional/perfil': {
      id: '/_authenticated/profesional/perfil'
      path: '/profesional/perfil'
      fullPath: '/profesional/perfil'
      preLoaderRoute: typeof AuthenticatedProfesionalPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profesional/oportunidades': {
      id: '/_authenticated/profesional/oportunidades'
      path: '/profesional/oportunidades'
      fullPath: '/profesional/oportunidades'
      preLoaderRoute: typeof AuthenticatedProfesionalOportunidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profesional/mensajes': {
      id: '/_authenticated/profesional/mensajes'
      path: '/profesional/mensajes'
      fullPath: '/profesional/mensajes'
      preLoaderRoute: typeof AuthenticatedProfesionalMensajesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profesional/cotizaciones': {
      id: '/_authenticated/profesional/cotizaciones'
      path: '/profesional/cotizaciones'
      fullPath: '/profesional/cotizaciones'
      preLoaderRoute: typeof AuthenticatedProfesionalCotizacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensajes/$id': {
      id: '/_authenticated/mensajes/$id'
      path: '/mensajes/$id'
      fullPath: '/mensajes/$id'
      preLoaderRoute: typeof AuthenticatedMensajesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/solicitudes': {
      id: '/_authenticated/cliente/solicitudes'
      path: '/cliente/solicitudes'
      fullPath: '/cliente/solicitudes'
      preLoaderRoute: typeof AuthenticatedClienteSolicitudesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/mensajes': {
      id: '/_authenticated/cliente/mensajes'
      path: '/cliente/mensajes'
      fullPath: '/cliente/mensajes'
      preLoaderRoute: typeof AuthenticatedClienteMensajesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/verificaciones': {
      id: '/_authenticated/admin/verificaciones'
      path: '/verificaciones'
      fullPath: '/admin/verificaciones'
      preLoaderRoute: typeof AuthenticatedAdminVerificacionesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/profesional/oportunidades/$id': {
      id: '/_authenticated/profesional/oportunidades/$id'
      path: '/$id'
      fullPath: '/profesional/oportunidades/$id'
      preLoaderRoute: typeof AuthenticatedProfesionalOportunidadesIdRouteImport
      parentRoute: typeof AuthenticatedProfesionalOportunidadesRoute
    }
    '/_authenticated/cliente/solicitudes/nueva': {
      id: '/_authenticated/cliente/solicitudes/nueva'
      path: '/nueva'
      fullPath: '/cliente/solicitudes/nueva'
      preLoaderRoute: typeof AuthenticatedClienteSolicitudesNuevaRouteImport
      parentRoute: typeof AuthenticatedClienteSolicitudesRoute
    }
    '/_authenticated/cliente/solicitudes/$id': {
      id: '/_authenticated/cliente/solicitudes/$id'
      path: '/$id'
      fullPath: '/cliente/solicitudes/$id'
      preLoaderRoute: typeof AuthenticatedClienteSolicitudesIdRouteImport
      parentRoute: typeof AuthenticatedClienteSolicitudesRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminVerificacionesRoute: typeof AuthenticatedAdminVerificacionesRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminVerificacionesRoute: AuthenticatedAdminVerificacionesRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedClienteSolicitudesRouteChildren {
  AuthenticatedClienteSolicitudesIdRoute: typeof AuthenticatedClienteSolicitudesIdRoute
  AuthenticatedClienteSolicitudesNuevaRoute: typeof AuthenticatedClienteSolicitudesNuevaRoute
}

const AuthenticatedClienteSolicitudesRouteChildren: AuthenticatedClienteSolicitudesRouteChildren =
  {
    AuthenticatedClienteSolicitudesIdRoute:
      AuthenticatedClienteSolicitudesIdRoute,
    AuthenticatedClienteSolicitudesNuevaRoute:
      AuthenticatedClienteSolicitudesNuevaRoute,
  }

const AuthenticatedClienteSolicitudesRouteWithChildren =
  AuthenticatedClienteSolicitudesRoute._addFileChildren(
    AuthenticatedClienteSolicitudesRouteChildren,
  )

interface AuthenticatedProfesionalOportunidadesRouteChildren {
  AuthenticatedProfesionalOportunidadesIdRoute: typeof AuthenticatedProfesionalOportunidadesIdRoute
}

const AuthenticatedProfesionalOportunidadesRouteChildren: AuthenticatedProfesionalOportunidadesRouteChildren =
  {
    AuthenticatedProfesionalOportunidadesIdRoute:
      AuthenticatedProfesionalOportunidadesIdRoute,
  }

const AuthenticatedProfesionalOportunidadesRouteWithChildren =
  AuthenticatedProfesionalOportunidadesRoute._addFileChildren(
    AuthenticatedProfesionalOportunidadesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMiPerfilRoute: typeof AuthenticatedMiPerfilRoute
  AuthenticatedNotificacionesRoute: typeof AuthenticatedNotificacionesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedClienteMensajesRoute: typeof AuthenticatedClienteMensajesRoute
  AuthenticatedClienteSolicitudesRoute: typeof AuthenticatedClienteSolicitudesRouteWithChildren
  AuthenticatedMensajesIdRoute: typeof AuthenticatedMensajesIdRoute
  AuthenticatedProfesionalCotizacionesRoute: typeof AuthenticatedProfesionalCotizacionesRoute
  AuthenticatedProfesionalMensajesRoute: typeof AuthenticatedProfesionalMensajesRoute
  AuthenticatedProfesionalOportunidadesRoute: typeof AuthenticatedProfesionalOportunidadesRouteWithChildren
  AuthenticatedProfesionalPerfilRoute: typeof AuthenticatedProfesionalPerfilRoute
  AuthenticatedProfesionalVerificacionRoute: typeof AuthenticatedProfesionalVerificacionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMiPerfilRoute: AuthenticatedMiPerfilRoute,
  AuthenticatedNotificacionesRoute: AuthenticatedNotificacionesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedClienteMensajesRoute: AuthenticatedClienteMensajesRoute,
  AuthenticatedClienteSolicitudesRoute:
    AuthenticatedClienteSolicitudesRouteWithChildren,
  AuthenticatedMensajesIdRoute: AuthenticatedMensajesIdRoute,
  AuthenticatedProfesionalCotizacionesRoute:
    AuthenticatedProfesionalCotizacionesRoute,
  AuthenticatedProfesionalMensajesRoute: AuthenticatedProfesionalMensajesRoute,
  AuthenticatedProfesionalOportunidadesRoute:
    AuthenticatedProfesionalOportunidadesRouteWithChildren,
  AuthenticatedProfesionalPerfilRoute: AuthenticatedProfesionalPerfilRoute,
  AuthenticatedProfesionalVerificacionRoute:
    AuthenticatedProfesionalVerificacionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ProfesionalesRouteChildren {
  ProfesionalesIdRoute: typeof ProfesionalesIdRoute
}

const ProfesionalesRouteChildren: ProfesionalesRouteChildren = {
  ProfesionalesIdRoute: ProfesionalesIdRoute,
}

const ProfesionalesRouteWithChildren = ProfesionalesRoute._addFileChildren(
  ProfesionalesRouteChildren,
)

interface ServiciosRouteChildren {
  ServiciosCategoriaRoute: typeof ServiciosCategoriaRoute
}

const ServiciosRouteChildren: ServiciosRouteChildren = {
  ServiciosCategoriaRoute: ServiciosCategoriaRoute,
}

const ServiciosRouteWithChildren = ServiciosRoute._addFileChildren(
  ServiciosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ProfesionalesRoute: ProfesionalesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ServiciosRoute: ServiciosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
